---
title: "Exercise set 2"
author: "Hien Le"
date: "05/11/2021"
output: Exercise set 2
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/student_data/BBT.BI.202_2021/students/leh/exercise_2")
```

## Exercise 1.

### Loading and inspecting the data

```{r E1-Q1.1}
## add you code here
count_matrix <- readRDS("count_matrix.RDS") #loading data
head(count_matrix) #seeing the header
df_count_matrix <- data.frame(rowSums(count_matrix))
colSums(df_count_matrix == 0)

    ```



```{r hint-1}
count_matrix[grep("ENSG00000204479", row.names(count_matrix)), ]
```



```{r E1-Q1.3}
## add you code here
?apply
row_medians <- apply(count_matrix, 1, median)
boxplot(row_medians, ylim = c(0,1800))

```


### Filtering

```{r E1-Q1.4}
## add you code here
threshold <- quantile(row_medians, 0.25, na.rm=FALSE, names = TRUE)
threshold

df_row_medians <- data.frame(apply(count_matrix, 1, median))
colSums(df_row_medians <= threshold)


```



```{r hint-2}
## inspect this code chunk to get some idea how to remove genes required in E1-Q1.7. Note that this is not the full answer...
test_df = data.frame(c(8, 120, 10, 49, 19), c(12,33,101,45,247), fix.empty.names=F)
valid_rows = rowSums(test_df) > 100
test_df[valid_rows,]
```



```{r E1-Q1.7}
## add you code here
df_count_matrix <- data.frame(count_matrix, fix.empty.names=F)
valid_rows <- df_row_medians > threshold
count_matrix_filtered <- df_count_matrix[valid_rows,]
count_matrix_filtered

```



### Before normalization

```{r E1-Q1.9}
## add you code here
par(las = 2)
boxplot(count_matrix_filtered[ยง1q], ylim = c(0,4000))

```



### Median of ratios normalization

```{r E1-Q1-NORMALIZATION}

library(DESeq2)

## preparing the sample_types that is going to assigned to colData argument in DESeqDataSetFromMatrix() function 
column_names = colnames(count_matrix_filtered)
column_names
sample_types = matrix(sub(pattern="_.*", 
                          replacement="", 
                          column_names)
                      )

rownames(sample_types) = column_names
colnames(sample_types) = c("Type")

## creating the data set expected by DESeq2

dataset <- DESeqDataSetFromMatrix(countData=count_matrix_filtered, colData=sample_types, design=~1)
dataset <- estimateSizeFactors(dataset) 

count_matrix_filtered_mor_normed <- counts(dataset, 
                                           normalized=TRUE) 
```



### After normalization

```{r E1-Q1.12}
## add you code here
par(las = 2)
boxplot(count_matrix_filtered_mor_normed[1-20,], ylim = c(0,4000))
```



## Exercise 2.

### Hierarchical clustering

```{r hint-3}
## This code chunk shows how to create a nested for loop

time_of_the_day = c("morning", "afternoon", "evening")
colors = c("salmon", "lavender")

print("Wake up! It's time!")
for (time in time_of_the_day){
    for (color in colors){
      title = sprintf("    Let's paint our %s %s!", time, color)
      print(title)
  }
  print('. and then ...')
}
print("Let's go to sleep!")
```



```{r E2-Q1.1}
## add you code here
linkage_methods <- c("ward.D", "ward.D2", "single", "complete", "average",  "mcquitty", "median", "centroid" )
distance_metrics <- c("euclidean", "maximum", "manhattan", "canberra", "binary" , "minkowski") 
for (link in linkage_methods){
    for (distance in distance_metrics){
      tree <- hclust(dist(count_matrix_filtered_mor_normed, method = distance), method = link)
      plot(tree, labels =  sprintf("linkage '%s', metric '%s'", link, distance))
  }
}


```



```{r E2-Q1.4.1}
correlation_dist = function(x, method="pearson"){
  
  ## complete the function here
  corr_distance = as.dist((1 - cor(x, y = NULL, method = method))/2) ## use the formula from example in ?dist manual here
  return(corr_distance) ## the class of the return value should be 'dist'
}

```



```{r E2-Q1.4.2}
## calling our correlation_dist() function over the first 3 samples ("BPH_456" "BPH_651" "BPH_652")
## method: pearson
round(correlation_dist(count_matrix_filtered_mor_normed[,  1:3], method ='pearson'), 2)
```



```{r E2-Q1.4.3}
## calling our correlation_dist() function over the first 3 samples ("BPH_456" "BPH_651" "BPH_652")
## method: spearman
round(correlation_dist(count_matrix_filtered_mor_normed[, 1:3], method ='spearman'), 2)
```



```{r E2-Q1.8}
## add you code here
hc <- hclust(correlation_dist(count_matrix_filtered_mor_normed), "complete")
plot(hc)
```



```{r E2-Q1.9}
## add you code here
hc <- hclust(correlation_dist(count_matrix_filtered_mor_normed, method ="spearman"), "complete")
plot(hc)

```



## Exercise 3. 

### Principal component analysis (PCA)

```{r hint-4}

# this says that we want to rotate our point 90 degrees counterclockwise.
# we have to multiply by pi and divide by 180 to convert radian to degrees.
theta = 90 * pi / 180  

# Here we define our rotation matrix
rotation = matrix(c(cos(theta), -sin(theta), sin(theta), cos(theta)), byrow = TRUE, nrow = 2)

# Here we plot some lines that are going to help us better see what happens during rotation
par(pty="s")
plot(c(-6, 6, -6, 6), c(-6, 6, 6, -6), type='l', xlim=c(-5, 5), ylim=c(-5, 5), xlab='x', ylab='y')
abline(h=0, v=0)

# This is our point before rotation
point_before_rotation = matrix(c(1,1), nrow = 1)

# This expression rotates our point 
point_after_rotation = t(rotation %*% t(point_before_rotation))

points(point_before_rotation, col='red')

points(point_after_rotation, col='green')
```



```{r E3-Q2.1}
## add you code here
pca_result <- prcomp(x=t(count_matrix_filtered_mor_normed), retx = TRUE, center = TRUE, scale. = TRUE)
str(pca_result)
```


```{r E3-Q2.3}
## add you code here
ncol(pca_result$rotation)
nrow(pca_result$rotation)
points2 <-t(t(pca_result$rotation[,1:2])%*%count_matrix_filtered_mor_normed)
dim(points2)
points2
```


```{r E3-Q2.6}
## add you code here
points <- pca_result$rotation
BPH_points <- points[1:5,]
PC_points <- points[6:20,]
plot(BPH_points,xlab="BPH Samples", ylab="Expression level", main="Scatterplot of the BPH data", col = "red")
plot(PC_points,xlab="PC Samples", ylab="Expression level", main="Scatterplot of the PC data", col = "green")
text(PC_points, labels=row.names(PC_points),data=PC_points, cex=0.9, font=2)

plot(points2, col="red")
points(points2[1:5,], col="green")
```


```{r E3-Q2.8}
## add you code here
pca.var <- pca_result$sdev^2
pca.var <- as.matrix(pca.var)
pca.var <- (pca.var/sum(pca.var))*100
dim(pca.var)
barplot(t(pca.var),mains="Scree plot", xlab="principal components", ylab="Percen variation", ylim=c(0,100))
```


```{r E3-Q2.9}
## add you code here
round(sum(pca.var[1:2,]),2)
```


```{r E3-Q2.11}
## add you code here
which.min(pca_result$rotation[,1])
which.max(pca_result$rotation[,1])
```



### Convert Ensmbl gene ID to gene name

``` {r  E3-Q2.14}

to_convert = c() ## complete this line with the results you got from E3-Q2.11


library('biomaRt')
mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))

mappings <- getBM(
                  filters= "ensembl_gene_id", 
                  attributes = c("ensembl_gene_id","hgnc_symbol"),
                  values=to_convert, 
                  mart= mart) 

mappings
```



## Exercise 4. 

## Data visualization using _ggplot2_ package

```{r E4-Q1.3}
## add you code here
library(ggplot2)
ggplot(count_matrix, aes(x=BPH_651, y=BPH_688)) + geom_point()
```



```{r E4-Q1.4}
## add you code here
count_matrix_add_1 <- count_matrix + 1
count_matrix_log2 <- log2(count_matrix_add_1)
ggplot(count_matrix_log2, aes(x=BPH_651, y=BPH_688)) + geom_point()

ggplot(count_matrix_log2, aes(x=PC_9324, y=PC_17163)) + geom_point()
```



```{r E4-Q1.5}
## add you code here
ggplot(count_matrix_log2, aes(x=PC_9324, y=PC_17163)) + geom_point()
```



```{r hint-5}
ggplot(data = #add the variable that stores the log2 transformed data here) 
+ geom_point(mapping = aes(x = PC_9324))
```


```{r E4-Q1.9}
random_sites = read.table(file="/student_data/BBT.BI.202_2021/data/week_2/random_sites.bed", sep='\t')
ggplot(data=random_sites)+
  geom_bar(mapping = aes(x=V4, color=V6)) +  ## complete the code here
    facet_wrap(~V5) ## complete the code here
```


## Exercise 5. 

```{r E5}
## add you code here
library(ggplot2)
pca <- prcomp(x=t(count_matrix_filtered_mor_normed), retx = TRUE, center = TRUE, scale. = TRUE)

pca.data <- data.frame(Sample=row.names(pca$x), X=pca$x[,1], Y=pca$x[,2]) 
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100,1)
par(pty="s")
ggplot(data=pca.data,aes(x=X,y=Y, label=Sample)) + geom_text() + xlab(paste("PC1 - ", pca.var.per[1], "%", sep="")) + ylab(paste("PC2 - ", pca.var.per[2], "%", sep="")) + theme_bw() + ggtitle("PCA analysis of Prostate cancer gene expression data")

```


